id: ed93d3a3-70e8-49da-aa42-1b0bf59b4062
#  opnrvn-r-89
refId: gcp-compute-ensure-instances-are-not-configured-to-use-the-default-service-account
type: asset
name: >
  Ensure that instances are not configured to use the default service account
description: >
  To support principle of least privileges and prevent potential privilege escalation
  it is recommended that instances are not assigned to default service account Compute Engine default service account
  with Scope Allow full access to all Cloud APIs.
severity: high
enabled: true
sql: >
  SELECT acc.assetid
    FROM ${magpie_schema}.gcpcomputeinstance acc,
    LATERAL (
          SELECT jsonb_array_elements_text(value -> 'scopes') as scp
          FROM jsonb_array_elements(configuration -> 'serviceAccounts')
    ) arr
   WHERE acc.resourcetype = 'GCP::ComputeEngine::Instance'
     AND scp = 'https://www.googleapis.com/auth/cloud-platform'

remediationDocURLs: https://github.com/openraven/security-rules/wiki
version: 0.2.6